apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  ports:
  - port: 8086
    name: influx8086
  selector:
    app: influxdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:alpine
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-pv
        - mountPath: /etc/influxdb/influxdb.conf
          name: influxdb-config
          subPath: influxdb.conf
          readOnly: true
        envFrom:
        - secretRef:
            name: influxdb-secrets
      volumes:
      - name: influxdb-pv
        persistentVolumeClaim:
          claimName: influxdb-pvc
      - name: influxdb-config
        configMap:
          name: influxdb-config 
