apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
#  type: NodePort
  ports:
  - port: 20
    name: nginx-ssh20
#    targetPort: 20
#    nodePort: 20
  - port: 80
    name: nginx80
    targetPort: 80
#    nodePort: 80
  - port: 443
    name: nginx443
#    nodePort: 443
    targetPort: 443
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          hostPort: 20
        - containerPort: 80
        - containerPort: 443
