apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    name: telegraf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf:alpine
        volumeMounts:
        - mountPath: /etc/telegraf/telegraf.conf
          name: telegraf-config
          subPath: telegraf.conf
          readOnly: true
        envFrom:
        - secretRef:
            name: telegraf-secrets
      volumes:
      - name: telegraf-config
        configMap:
          name: telegraf-config
