apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  ports:
  - port: 21
    name: ftps21
  - port: 64000
    name: ftps-pasv-64000
  - port: 64001
    name: ftps-pasv-64001
  - port: 64002
    name: ftps-pasv-64002
  - port: 64003
    name: ftps-pasv-64003
  - port: 64004
    name: ftps-pasv-64004
  - port: 64005
    name: ftps-pasv-64005
  - port: 64006
    name: ftps-pasv-64006
  - port: 64007
    name: ftps-pasv-64007
  - port: 64008
    name: ftps-pasv-64008
  - port: 64009
    name: ftps-pasv-64009
  - port: 64010
    name: ftps-pasv-64010
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          hostPort: 21
        - containerPort: 64000
          hostPort: 64000
        - containerPort: 64001
          hostPort: 64001
        - containerPort: 64002
          hostPort: 64002
        - containerPort: 64003
          hostPort: 64003
        - containerPort: 64004
          hostPort: 64004
        - containerPort: 64005
          hostPort: 64005
        - containerPort: 64006
          hostPort: 64006
        - containerPort: 64007
          hostPort: 64007
        - containerPort: 64008
          hostPort: 64008
        - containerPort: 64009
          hostPort: 64009
        - containerPort: 64010
          hostPort: 64010
        volumeMounts:
        - mountPath: /srv
          name: ftps-pv
      volumes:
      - name: ftps-pv
        persistentVolumeClaim:
          claimName: ftps-pvc
